create table
  hotel (
    id bigint generated by default as identity primary key,
    name text null
  );

create table
  booking (
    id bigint generated by default as identity primary key,
    hotel_id bigint, -- nullable foreign key is needed to reproduce !inner supabase-js error
    foreign key (hotel_id) references hotel (id)
  );
